
import { StackProvider, StackTheme } from "@stackframe/stack";
import { stackServerApp } from "../stack";
import "./globals.css";
import Provider from "./provider";


export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body
        className=""
      >
       
        <StackProvider app={stackServerApp}><StackTheme>
        <Provider>
        {children}
        </Provider>
      </StackTheme></StackProvider>
        
      
      
        
      
      </body>
    </html>
  );
}
